### ISSUE TITLE
flow-sample-basic falls with ClassNotFoundException due to "Didn't find class "android.support.design.widget.TextInputLayout"

### ISSUE THREAD

**Issue by VladimirMi** [Zhuinden/flowless#29]
I do not find dependency for support design library in the build.gradle file.

**Comment by Zhuinden** [comment]
Whoops! I added the dependency now.

I *did* just bring that one over without running it, I guess I shouldn't have trusted its build.gradle ^_^

If you find anything else, give a holler - although everything else should work, I did try out every other example after all

**Comment by Zhuinden** [comment]
Thanks for the report.
